[package]
name = "feu-adapter-hyper"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.11.0"
feu-core = { version = "0.1.0", path = "../../feu-core" }
http = "1.4.0"
http-body-util = "0.1.3"
hyper = { version = "1.8.1", features = ["full"] }
hyper-util = { version = "0.1.19", features = ["full"] }
tokio = { version = "1.49.0", features = ["full"] }
