[package]
name = "feu-middleware"
version = "0.1.0"
edition = "2021"

[dependencies]
feu-core = { version = "0.1.0", path = "../feu-core" }
http = "1.4.0"
sha1 = "0.10.6"
tokio = { version = "1.49.0", features = ["macros", "rt", "rt-multi-thread", "time"] }
tracing = "0.1.44"
uuid = { version = "1.19.0", features = ["v4", "fast-rng"] }
